# Auto-ablation with Howso Engine

> Note: This feature is experimental and is not universally recommended for production deployment.

## Overview

This notebook provides an overview of using auto-ablation during train to reduce the size of your data _as they are trained_.

In [1]:
import pandas as pd
from pmlb import fetch_data

from howso.engine import Trainee
from howso.utilities import infer_feature_attributes

## Step 1: Load Data & Feature Mapping

Our example dataset for this recipe is the well-known `Adult` dataset. This dataset works well because it has over 48,000 cases. In general, datasets containing over 25,000 rows work well. The default minimum size is 1,000 cases, below which no cases will be ablated.

This part of the process is identical to other recipes.

In [2]:
df = fetch_data("adult", local_cache_dir="../../../data")
features = infer_feature_attributes(df, fanout_feature_map={"education_num": ["education"]})

display(df)
display(features.to_dataframe())

Feature Attributes Summary

  · Found 9 rare values across 2 columns whose signal may be lost during data distillation workflows

  Inspect `your_attributes_object.suggestions` for details and how to apply them.

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,target
0,39.0,7,77516.0,9,13.0,4,1,1,4,1,2174.0,0.0,40.0,39,1
1,50.0,6,83311.0,9,13.0,2,4,0,4,1,0.0,0.0,13.0,39,1
2,38.0,4,215646.0,11,9.0,0,6,1,4,1,0.0,0.0,40.0,39,1
3,53.0,4,234721.0,1,7.0,2,6,0,2,1,0.0,0.0,40.0,39,1
4,28.0,4,338409.0,9,13.0,2,10,5,2,0,0.0,0.0,40.0,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39.0,4,215419.0,9,13.0,0,10,1,4,0,0.0,0.0,36.0,39,1
48838,64.0,0,321403.0,11,9.0,6,0,2,2,1,0.0,0.0,40.0,39,1
48839,38.0,4,374983.0,9,13.0,2,10,0,4,1,0.0,0.0,50.0,39,1
48840,44.0,4,83891.0,9,13.0,0,1,3,1,1,5455.0,0.0,40.0,39,1
48841,35.0,5,182148.0,9,13.0,2,4,0,4,1,0.0,0.0,60.0,39,0

                      type decimal_places bounds                        \
                                             min        max allow_null
age             continuous              0    0.0      137.0       True
workclass          nominal              0    NaN        NaN       True
fnlwgt          continuous              0    0.0  2449285.0       True
education          nominal              0    NaN        NaN       True
education-num   continuous              0    0.0       26.0       True
marital-status     nominal              0    NaN        NaN       True
occupation         nominal              0    NaN        NaN       True
relationship       nominal              0    NaN        NaN       True
race               nominal              0    NaN        NaN       True
sex                nominal              0    NaN        NaN       True
capital-gain    continuous              0    0.0   164870.0       True
capital-loss    continuous              0    0.0     7182.0       True
hours-per-week  continuous              0    0.0      163.0       True
native-country     nominal              0    NaN        NaN       True
target             nominal              0    NaN        NaN       True

                                                        data_type  \
               observed_min observed_max nulls_observed
age                    17.0         90.0          False    number
workclass               NaN          NaN          False    number
fnlwgt              12285.0    1490400.0          False    number
education               NaN          NaN          False    number
education-num           1.0         16.0          False    number
marital-status          NaN          NaN          False    number
occupation              NaN          NaN          False    number
relationship            NaN          NaN          False    number
race                    NaN          NaN          False    number
sex                     NaN          NaN          False    number
capital-gain            0.0      99999.0          False    number
capital-loss            0.0       4356.0          False    number
hours-per-week          1.0         99.0          False    number
native-country          NaN          NaN          False    number
target                  NaN          NaN          False    number

                      fanout_on original_type
                                    data_type size
age                         NaN       numeric    8
workclass                   NaN       integer    8
fnlwgt                      NaN       numeric    8
education       [education_num]       integer    8
education-num               NaN       numeric    8
marital-status              NaN       integer    8
occupation                  NaN       integer    8
relationship                NaN       integer    8
race                        NaN       integer    8
sex                         NaN       integer    8
capital-gain                NaN       numeric    8
capital-loss                NaN       numeric    8
hours-per-week              NaN       numeric    8
native-country              NaN       integer    8
target                      NaN       integer    8

## Step 3: Create Trainee and Set Parameters

The process of creating the `Trainee` is the same as the other recipes. However, after the `Trainee` is created, we set auto-analyze and auto-ablation parameters to ensure that the `Trainee` remains informed as it removes cases during train.

In [3]:
t = Trainee(features=features)

# Set auto-analyze parameters. Note that use_case_weights=True since case-weights are how
# information from ablated cases is retained in the Trainee.
t.set_auto_analyze_params(auto_analyze_enabled=True, use_case_weights=True)

# Set auto-ablation parameters.
t.set_auto_ablation_params(
    auto_ablation_enabled=True,
    influence_weight_entropy_threshold=0.6,
    min_num_cases=2_500,
    max_num_cases=10_000,
    delta_threshold_map={
        "accuracy": {"target": 0.1}
    }
)

This recipe uses the following parameters for auto-ablation:

- `auto_ablation_enabled` — When this parameter is `False`, auto-ablation will not be performed.
- `influence_weight_entropy_threshold` — This parameter is used to determine which cases will be ablated.
  If the entropy of a case's influence weights would be above this percentile of existing cases' influence
  weight entropies, then the case is ablated. This is set to $0.6$, the default value.
- `min_num_cases` — This parameter sets the minimum number of cases that are allowed to be in the Trainee.
- `max_num_cases` — This parameter sets the maximum number of cases that are allowed to be in the Trainee.
- `delta_threshold_map` — This parameter defines thresholds that are used to determine when ablation should stop.
  In this case, the threshold map instructs auto-ablation to stop if the delta between the current accuracy
  of the `"target"` feature and its previous accuracy is greater than $0.1$. I.e., ablation will stop if accuracy
  for that feature drops from $0.8$ to $0.7$. More formally, ablation will stop if
  $\text{acc}_\text{old} - \text{acc}_\text{new} \geq 0.1$.

## Step 4: Training

Now that the parameters are set, the `Trainee` can be trained as if this were a normal workflow.

In [4]:
t.train(df)

✓ Train complete in 0:01:08

Notably, only a subset of the cases have been trained (the rest have been ablated).

In [5]:
num_trained_cases = t.get_num_training_cases()
num_total_cases = len(df)
num_trained_percent = round((num_trained_cases / num_total_cases) * 100, 3)

print(f"Trained {num_trained_cases:,} cases out of {num_total_cases:,} ({num_trained_percent}%).")

Trained 6,374 cases out of 48,842 (13.05%).

## Step 5: Results

An ablated `Trainee` can be used in much the same way as other `Trainee`s, as long as `use_case_weights=True`. Here, we will investigate the prediction stats for all features.

In [6]:
stats = t.react_aggregate(
    prediction_stats_action_feature="target",
    details={
        "prediction_stats": True,
        "selected_prediction_stats": ["all"],
    },
    use_case_weights=True,
)

stats_df = stats.to_dataframe()
stats_df

,relationship,sex,marital-status,race,occupation,workclass,native-country,target,education,hours-per-week,education-num,fnlwgt,age,capital-gain,capital-loss
accuracy,0.836000,0.869000,0.927000,0.948000,0.243000,0.886000,0.966700,0.851000,1.0,NaN,NaN,NaN,NaN,NaN,NaN
adjusted_smape,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.063563,0.002339,44.899796,20.200078,168.521030,180.276272
mae,0.208080,0.160750,0.095776,0.075589,0.794017,0.168921,0.060088,0.184555,0.0,6.146235,0.000244,81324.727234,7.708432,1555.701263,168.164941
mcc,0.732887,0.543233,0.868592,0.219099,0.125944,0.425974,0.429413,0.554963,1.0,NaN,NaN,NaN,NaN,NaN,NaN
missing_value_accuracy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
precision,0.507829,0.770999,0.510154,0.356979,0.217349,0.421693,0.317730,0.780839,1.0,NaN,NaN,NaN,NaN,NaN,NaN
r2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.111428,0.999996,-0.013613,0.384300,0.139955,-0.050620
recall,0.445493,0.772235,0.492181,0.282489,0.144684,0.311493,0.228121,0.774164,1.0,NaN,NaN,NaN,NaN,NaN,NaN
rmse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.142850,0.005085,111605.865557,10.256445,7026.400198,394.988985
smape,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.291579,0.002456,44.899938,20.489924,174.110356,185.760925
spearman_coeff,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.327364,0.962579,0.021563,0.621871,0.535305,0.455798

In [7]:
# The confusion matrix can be retrieved
print("Howso Prediction Results - Confusion Matrix for 'target'")
matrix = pd.DataFrame(stats['confusion_matrix']['target']["matrix"])
matrix.index.name = "Predicted"
matrix.columns.name = "Actual"
display(matrix)

Howso Prediction Results - Confusion Matrix for 'target'

Actual       0    1
Predicted
0          138   71
1           78  713

## Conclusion

Howso Engine with auto-ablation can compress data to a fraction of its original size while ensuring accuracy (and other measures) remain in an acceptable range without compromising the other capabilities of the `Trainee`.