# Clustering With Howso Engine

## Overview

This example notebook will demonstrate Howso Engine’s ability to calculate pairwise distances for the training cases. This capability is based on Howso Engine’s underlying instance-based learning platform. Distances can be used for a variety of use cases, in particular, for clustering algorithms, such as HDBSCAN. Howso Engine’s feature reduction capabilities will also be used to demonstrate how to eliminate features for clustering.

In [1]:
import numpy as np
import pandas as pd
from plotly.subplots import make_subplots
from sklearn.cluster import HDBSCAN
from sklearn.datasets import make_blobs
from sklearn.metrics import adjusted_rand_score

from howso import engine
from howso.utilities import infer_feature_attributes
from howso.visuals import plot_umap

### Step 1: Generate a simple dataset with noise

A 2-D blob is generated along with an extra noise column. The noise column is used to demonstrate feature reduction.

In [2]:
blobs = make_blobs(n_samples=100, n_features=2, centers=[(1,0), (1,5), (10,2)], random_state=0)
df = pd.DataFrame(blobs[0], columns=['x', 'y'])
df['target'] = blobs[1]

# Noise
noise = np.random.uniform(df['y'].min(), df['y'].max(), len(df))
df['noise'] = noise

### Step 2: Create the Trainee, Train, and Analyze

For questions about the specific steps of this section, please see the [basic workflow guide](https://docs.howso.com/en/release-latest/user_guide/basic_capabilities/basic_workflow.html).

In [3]:
# Infer feature attributes
features = infer_feature_attributes(df)

# Create the Trainee
t = engine.Trainee(features=features, overwrite_existing=True)

# Train
t.train(df)

t.analyze()

/Users/cmack/dev/howso-engine-py/howso/utilities/feature_attributes/pandas.py:145: UserWarning: You have one or more suggestions to consider for your feature attributes configuration. Please view them by printing the `suggestions` property of your returned feature attributes object (`your_attributes_object.suggestions`).
  warnings.warn(suggestion_warning, UserWarning)
Version 61.1.1 of Howso Engine™ is available. You are using version 60.2.2.dev1+gf53f28231.
The following parameters from your configuration will override the default Amalgam parameters: {'trace', 'library_path'}

### Step 3: Inspect Feature Importance

In this example, since we have a target feature, we can inspect the [Accuracy Contributions](https://docs.howso.com/en/release-latest/getting_started/terminology.html#accuracy-contributions-ac) (a form of MDA) to understand how important each feature is.

In [4]:
# Specify Context and Action Features
action_features = ['target']
context_features = features.get_names(without=action_features)

results = t.react_aggregate(
    context_features=context_features,
    feature_influences_action_feature=action_features[0],
    details={
        "feature_robust_prediction_contributions": True,
        "feature_robust_accuracy_contributions": True
    }
)

In [5]:

# Robust Accuracy Contributions are returned as a matrix, the result must be edited to
# view the contributions of the target feature in a row as the other metrics.
robust_feature_influences = results['feature_robust_accuracy_contributions'].drop(['target'], axis=0)
robust_feature_influences

                                 target
noise  [0.0007038000589035254, None, 0]
y         [0.3781848088342321, None, 0]
x         [0.2867288795511224, None, 0]

We can see that the noise column not only contributes less to the prediction than the other variables, but it also marginally increases (and perhaps lowers) the accuracy. This is expected from the noise column and demonstrates how unimportant features can be highlighted with Howso Engine.

### Step 4: Remove Unuseful Features

Unuseful features like the noise feature can reduce the quality of the clustering so we will remove them in this example. Howso Engine allows use to easily remove the features from the Trainee.

In [6]:
# Remove the noise feature
t.remove_feature('noise')

# update context_features
context_features.remove('noise')

t.analyze()

## Step 5: Get pairwise distances

By directly using Howso Engine's pairwise distances, we can take advantage of all the benefits of Howso Engine, including the ease of preprocessing and categorical variable handling. 

`get_distances` returns a square matrix of distances that make up the pairwise distances from each case to each other case in the model. The distances are computing using the Howso Engine's internal distance metric which has its parameters tuned within the Analyze call. For more information about the Howso Engine's distance metric, see [<em>Surprisal Driven k-NN for Robust and Interpretable Nonparametric Learning </em> (Banerjee et. al. 2023)](https://arxiv.org/abs/2311.10246).

In [7]:
# Pairwise distances can be obtained with a call to `get_distances`
x = t.get_distances(features=context_features, sparse=False)["distances"]
# Howso can produce asymmetrical distances when nominal features are trained.
# This line remedies that.
x = x.combine(x.T, np.maximum)

x

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.000000,21.383414,0.112275,29.435530,30.660256,9.669556,5.165732,35.863493,37.568036,14.835828,...,5.279418,38.718130,34.165766,31.834706,3.374352,48.500835,38.975802,41.392497,37.372239,39.472044
1,21.383414,0.000000,20.962578,18.200663,17.679681,27.446153,18.186958,23.257723,56.882969,39.148384,...,14.590790,62.391841,58.281166,22.062606,18.003229,72.694319,27.116113,64.316619,57.638364,60.574337
2,0.112275,20.962578,0.000000,30.289018,31.513743,10.503055,4.540467,36.716983,38.383309,15.283947,...,4.839898,39.272297,34.649408,32.688196,2.735975,48.970803,39.829292,42.042636,38.167902,40.241564
3,29.435530,18.200663,30.289018,0.000000,0.536599,16.917324,36.041681,4.131455,36.375082,21.185050,...,31.276860,41.883953,37.773278,2.117197,34.518156,52.186431,7.641644,43.808731,37.130477,40.066449
4,30.660256,17.679681,31.513743,0.536599,0.000000,18.150160,37.266405,4.185520,38.192074,22.606303,...,32.501582,43.700946,39.590272,3.359266,35.742880,54.003424,8.156826,45.625724,38.947470,41.883442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,48.500835,72.694319,48.970803,52.186431,54.003424,42.258355,55.205261,47.954897,12.832748,34.031265,...,56.464854,7.706825,12.498558,47.973641,53.110678,0.000000,43.544164,5.569317,12.090286,9.175122
96,38.975802,27.116113,39.829292,7.641644,8.156826,26.430078,45.581958,2.442609,27.732818,29.912329,...,40.817136,33.241687,29.131114,4.715923,44.058433,43.544164,0.000000,35.166464,28.488213,31.424183
97,41.392497,64.316619,42.042636,43.808731,45.625724,33.987119,48.053763,39.577196,4.693555,30.811585,...,48.201999,1.856220,7.971377,39.595941,46.227139,5.569317,35.166464,0.000000,4.071466,1.539130
98,37.372239,57.638364,38.167902,37.130477,38.947470,27.746400,43.994572,32.898942,0.083436,27.938477,...,41.992076,2.304914,5.019908,32.917688,42.384723,12.090286,28.488213,4.071466,0.000000,1.228894
99,39.472044,60.574337,40.241564,40.066449,41.883442,30.499390,46.101575,35.834915,1.599522,29.857016,...,44.732731,1.270604,6.883315,35.853660,44.452731,9.175122,31.424183,1.539130,1.228894,0.000000

## Step 6a: Cluster

Having access to the full matrix of pairwise distances, users have the ability to cluster with whatever algorithm they prefer (provided it supports a matrix of precomputed pairwise distances as an input).

In the case of this recipe, we demonstrate using the HDBSCAN provided through Scikit-Learn.

In [8]:
hdb = HDBSCAN(min_cluster_size=15, max_cluster_size=50, min_samples=10, metric='precomputed').fit(x)
hdbscan_labels = hdb.labels_
df["hdbscan_labels"] = hdbscan_labels

fig = make_subplots(rows=1, cols=2, subplot_titles=["True Clusters", "HDBSCAN Clusters"])
for label, group in df.groupby("target"):
    fig.add_scatter(x=group.x, y=group.y, col=1, row=1, mode="markers", name=label)
for label, group in df.groupby("hdbscan_labels"):
    fig.add_scatter(
        x=group.x, y=group.y, col=2, row=1, mode="markers", name=label,
        marker_color=fig.layout["template"]["layout"]["colorway"][label],
        showlegend=False
    )
fig.show()

/Users/cmack/.py_envs/scratch/lib/python3.13/site-packages/sklearn/cluster/_hdbscan/hdbscan.py:722: FutureWarning: The default value of `copy` will change from False to True in 1.10. Explicitly set a value for `copy` to silence this warning.
  warn(

## Step 6b: Visualize with UMAP

UMAP can be used in tandem with Howso Engine to visualize high-dimensional datasets, similar to how HDBSCAN is used.

In [9]:
fig = plot_umap(t, color="target", action_feature=action_features[0])
fig.show()

## Step 7: Inspect Accuracy 

We calculate the performance of the clustering by measuring the similarity of the clusters compared to the original labels.

In [10]:
dist_contribution_acc = adjusted_rand_score(df['target'], hdbscan_labels)
print(f'clustering accuracy score: {dist_contribution_acc}')

clustering accuracy score: 0.9703067682010231

# Conclusion

As we demonstrate here, it is quite simple to use the Howso Engine for clustering using the internal distance metric by retrieving the pairwise distance matrix with `get_distances`. This pairwise distance metric can be passed to many popular clustering algorithms.