# Prediction Insights

## Overview

Howso Engine enables powerful predictions with complete attribution and detailed explanations to make learning from
and debugging your data and predictions as easy as possible. For more information on predictions with Howso Engine,
check out the [predictions user guide](https://docs.howso.com/en/release-latest/user_guide/basic_capabilities/predictions.html).

In [1]:
from pprint import pprint

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

from howso.engine import Trainee
from howso.utilities import infer_feature_attributes

## Setup

This recipe will focus on the insights gained from predictions. Specifically, insights from:

- Influential Cases,
- Feature Contributions,
- Residual and Similarity Conviction,
- and Categorical Action Probabilities.

The [basic workflow guide](https://docs.howso.com/en/release-latest/user_guide/basic_capabilities/basic_workflow.html) covers creating a Trainee and performing a basic react in detail.

### Load Data and Create Trainee

In [2]:
df = pd.read_csv("../../data/iris/iris.tsv.gz", sep="\t", compression="gzip", index_col=0)
train_data = df.iloc[:-30]
new_data = df[~df.index.isin(train_data.index)]
features = infer_feature_attributes(train_data)

t = Trainee(features=features)

df

     sepal length  sepal width  petal length  petal width            class
27            5.2          3.5           1.5          0.2      Iris-setosa
14            5.8          4.0           1.2          0.2      Iris-setosa
25            5.0          3.0           1.6          0.2      Iris-setosa
82            5.8          2.7           3.9          1.2  Iris-versicolor
97            6.2          2.9           4.3          1.3  Iris-versicolor
..            ...          ...           ...          ...              ...
126           6.2          2.8           4.8          1.8   Iris-virginica
124           6.7          3.3           5.7          2.1   Iris-virginica
78            6.0          2.9           4.5          1.5  Iris-versicolor
125           7.2          3.2           6.0          1.8   Iris-virginica
130           7.4          2.8           6.1          1.9   Iris-virginica

[150 rows x 5 columns]

### Train, Analyze, and React

In [3]:
t.train(train_data)
t.analyze()
t.react_into_features(similarity_conviction=True)

reaction = t.react(
    contexts=new_data,
    context_features=["sepal length", "sepal width", "petal length", "petal width"],
    action_features=["class"],
    details={
        "influential_cases": True,
        "similarity_conviction": True,
        "feature_robust_prediction_contributions": True,
        "feature_robust_residuals": True,
        "feature_full_residual_convictions_for_case": True,
        "categorical_action_probabilities": True,
    }
)

Note that, unlike in the basic workflow guide, we include several `details` in the react call and predict multiple cases as opposed to one. These are what will enable the
insights that we're going to get after the predictions are made.

For more information, see [the API documentation for `Trainee.react()`](https://docs.howso.com/en/release-latest/api_reference/_autosummary/howso.engine.html#howso.engine.Trainee.react).

### Inspect the Predictions

Howso Engine has high accuracy even on small datasets.

Here we see a comparison of the trained data (dots) and the predicted data (stars). This plot shows that the predictions align well with the trained data.

In [4]:
train_data = train_data.astype({"class": str})
predicted_data = pd.concat([new_data.reset_index(drop=True).drop(columns="class"), reaction["action"]], axis=1)
predicted_data = predicted_data.astype({"class": str})

cmap = px.colors.qualitative.D3
fig = go.Figure()
for i, (label, group) in enumerate(train_data.groupby("class")):
    fig.add_trace(go.Scatter(
        x=group["petal length"],
        y=group["petal width"],
        mode="markers",
        name=label,
        marker=dict(color=cmap[i], opacity=0.75),
        legendgroup="trained",
        legendgrouptitle_text="Trained class",
    ))

for i, (label, group) in enumerate(predicted_data.groupby("class")):
    fig.add_trace(go.Scatter(
        x=group["petal length"],
        y=group["petal width"],
        mode="markers",
        marker=dict(size=12, symbol="star", color=cmap[i], opacity=0.75),
        name=label,
        legendgroup="predicted",
        legendgrouptitle_text="Predicted class",
        hovertext=group.index,
    ))

fig.update_layout(
    xaxis_title="Petal Length",
    yaxis_title="Petal Width",
    title="Trained and Predicted Values"
)
fig.show(width=1000)

For categorical action features, the prediction can be further understood with the `categorical_action_probabilities` detail.  
This shows the probability of each possible value of the target feature. This information can highlight cases that are on the
border of two classes, like some of the above points are.  The closer a case gets to a class border, the more mixed the
categorical action probabilities may get.

In [5]:
pprint(reaction["details"]["categorical_action_probabilities"], compact=True)

[{'class': {'Iris-versicolor': 1}},
 {'class': {'Iris-versicolor': 0.14526212895342053,
            'Iris-virginica': 0.8547378710465795}},
 {'class': {'Iris-versicolor': 0.01874945499925027,
            'Iris-virginica': 0.9812505450007498}},
 {'class': {'Iris-versicolor': 0.01609927125989458,
            'Iris-virginica': 0.9839007287401054}},
 {'class': {'Iris-versicolor': 0.3112875245743747,
            'Iris-virginica': 0.6887124754256252}},
 {'class': {'Iris-versicolor': 1}}, {'class': {'Iris-setosa': 1}},
 {'class': {'Iris-versicolor': 0.05846626290713563,
            'Iris-virginica': 0.9415337370928644}},
 {'class': {'Iris-versicolor': 0.9751337352807287,
            'Iris-virginica': 0.02486626471927139}},
 {'class': {'Iris-versicolor': 1}}, {'class': {'Iris-virginica': 1}},
 {'class': {'Iris-versicolor': 0.9921744805608574,
            'Iris-virginica': 0.007825519439142531}},
 {'class': {'Iris-setosa': 1}},
 {'class': {'Iris-versicolor': 0.21874065654084757,
            'Iris-virginica': 0.7812593434591524}},
 {'class': {'Iris-versicolor': 0.9941643777918199,
            'Iris-virginica': 0.005835622208180143}},
 {'class': {'Iris-setosa': 1}}, {'class': {'Iris-setosa': 1}},
 {'class': {'Iris-versicolor': 0.3274550363471351,
            'Iris-virginica': 0.6725449636528649}},
 {'class': {'Iris-versicolor': 0.03608882876176177,
            'Iris-virginica': 0.9639111712382382}},
 {'class': {'Iris-versicolor': 0.93342538726164,
            'Iris-virginica': 0.06657461273836}},
 {'class': {'Iris-setosa': 1}}, {'class': {'Iris-versicolor': 1}},
 {'class': {'Iris-versicolor': 0.9953604269950092,
            'Iris-virginica': 0.004639573004990721}},
 {'class': {'Iris-setosa': 1}}, {'class': {'Iris-setosa': 1}},
 {'class': {'Iris-versicolor': 0.19515005823747864,
            'Iris-virginica': 0.8048499417625214}},
 {'class': {'Iris-versicolor': 0.0020090316803096707,
            'Iris-virginica': 0.9979909683196903}},
 {'class': {'Iris-versicolor': 0.9783384604234486,
            'Iris-virginica': 0.021661539576551463}},
 {'class': {'Iris-versicolor': 0.002571671385160761,
            'Iris-virginica': 0.9974283286148392}},
 {'class': {'Iris-virginica': 1}}]

For example, if we look at case `4`, we see a mix of probabilities because this case is on the border of two classes.

In [6]:
reaction["details"]["categorical_action_probabilities"][4]

{'class': {'Iris-virginica': 0.6887124754256252,
  'Iris-versicolor': 0.3112875245743747}}

### Insight 1: Which Cases Contributed?

Howso provides complete attribution for any and all predictions, showing exactly which cases influenced each prediction.  This can be used to understand or debug predictions.  For instance,
we can inspect the influential cases for one of the cases (case `4`) that was on the decision boundary in the plot above.  We can see that there is a mix of class values and no cases stand
out in terms of influence weight:

In [7]:
inf_cases_4 = reaction["details"]["influential_cases"][4]
inf_cases_4

,.session,sepal width,.influence_weight,petal length,class,petal width,.session_training_index,sepal length
0,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.8,0.237484,5.1,Iris-virginica,1.5,99,6.3
1,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.9,0.164975,5.6,Iris-virginica,1.8,61,6.3
2,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.5,0.139198,4.9,Iris-versicolor,1.5,107,6.3
3,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.2,0.099721,5.0,Iris-virginica,1.5,34,6.0
4,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.9,0.072612,4.7,Iris-versicolor,1.4,89,6.1
5,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.8,0.046065,4.7,Iris-versicolor,1.2,100,6.1
6,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.7,0.039757,5.3,Iris-virginica,1.9,103,6.4
7,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.1,0.028059,5.5,Iris-virginica,1.8,6,6.4
8,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.0,0.027815,4.6,Iris-versicolor,1.4,26,6.1
9,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.0,0.024684,5.5,Iris-virginica,1.8,66,6.5
10,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.7,0.020961,4.9,Iris-virginica,1.8,115,6.3
11,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.8,0.020574,5.6,Iris-virginica,2.1,36,6.4
12,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.7,0.015421,5.1,Iris-virginica,1.9,41,5.8
13,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.0,0.013736,5.1,Iris-virginica,1.8,8,5.9
14,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.0,0.012584,4.9,Iris-virginica,1.8,95,6.1
15,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.8,0.010757,5.6,Iris-virginica,2.2,46,6.4
16,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.2,0.009263,4.5,Iris-versicolor,1.5,86,6.2
17,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.8,0.006490,4.6,Iris-versicolor,1.5,25,6.5
18,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.9,0.005811,4.3,Iris-versicolor,1.3,4,6.2
19,606c7dd6-ba4b-4a0c-aab4-774556e50210,2.8,0.004035,4.5,Iris-versicolor,1.3,58,5.7

Compare that to the influential cases for case `20`, which is firmly in the center of the solo cluster.  Here we see a single class value.

In [8]:
inf_cases_20 = reaction["details"]["influential_cases"][20]
inf_cases_20

,.session,sepal width,.influence_weight,petal length,class,petal width,.session_training_index,sepal length
0,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.4,0.165022,1.7,Iris-setosa,0.2,9,5.4
1,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.4,0.104157,1.4,Iris-setosa,0.2,43,5.2
2,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.5,0.103297,1.5,Iris-setosa,0.2,0,5.2
3,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.7,0.100652,1.5,Iris-setosa,0.2,104,5.4
4,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.5,0.084673,1.4,Iris-setosa,0.3,48,5.1
5,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.4,0.077479,1.6,Iris-setosa,0.4,63,5.0
6,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.7,0.074670,1.5,Iris-setosa,0.2,68,5.3
7,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.4,0.068633,1.5,Iris-setosa,0.2,85,5.1
8,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.7,0.058411,1.5,Iris-setosa,0.4,117,5.1
9,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.3,0.056603,1.7,Iris-setosa,0.5,116,5.1
10,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.9,0.053202,1.3,Iris-setosa,0.4,21,5.4
11,606c7dd6-ba4b-4a0c-aab4-774556e50210,3.9,0.053202,1.7,Iris-setosa,0.4,47,5.4

With the influential cases we can derive additional insights, such as identifying anomalous cases from within the influential cases using `similarity_conviction`.  
This can help to identify data that are making predictions more noisy or identify what type of data should be collected to improve predictive power in the future.

In [9]:
inf_case_indices = inf_cases_4[[".session", ".session_training_index"]].values.tolist()

anom_df = t.get_cases(
    case_indices=inf_case_indices,
    features=["sepal length", "sepal width", "petal length", "petal width", "class", "similarity_conviction"]
)

anom_df.sort_values(by="similarity_conviction")

,sepal length,sepal width,petal length,petal width,class,similarity_conviction
0,6.3,2.8,5.1,1.5,Iris-virginica,None
1,6.3,2.9,5.6,1.8,Iris-virginica,None
2,6.3,2.5,4.9,1.5,Iris-versicolor,None
3,6.0,2.2,5.0,1.5,Iris-virginica,None
4,6.1,2.9,4.7,1.4,Iris-versicolor,None
5,6.1,2.8,4.7,1.2,Iris-versicolor,None
6,6.4,2.7,5.3,1.9,Iris-virginica,None
7,6.4,3.1,5.5,1.8,Iris-virginica,None
8,6.1,3.0,4.6,1.4,Iris-versicolor,None
9,6.5,3.0,5.5,1.8,Iris-virginica,None
10,6.3,2.7,4.9,1.8,Iris-virginica,None
11,6.4,2.8,5.6,2.1,Iris-virginica,None
12,5.8,2.7,5.1,1.9,Iris-virginica,None
13,5.9,3.0,5.1,1.8,Iris-virginica,None
14,6.1,3.0,4.9,1.8,Iris-virginica,None
15,6.4,2.8,5.6,2.2,Iris-virginica,None
16,6.2,2.2,4.5,1.5,Iris-versicolor,None
17,6.5,2.8,4.6,1.5,Iris-versicolor,None
18,6.2,2.9,4.3,1.3,Iris-versicolor,None
19,5.7,2.8,4.5,1.3,Iris-versicolor,None

In [10]:
inf_case_indices = inf_cases_20[[".session", ".session_training_index"]].values.tolist()

anom_df = t.get_cases(
    case_indices=inf_case_indices,
    features=["sepal length", "sepal width", "petal length", "petal width", "class", ".similarity_conviction"],
)

anom_df.sort_values(by=".similarity_conviction")

,sepal length,sepal width,petal length,petal width,class,.similarity_conviction
10,5.4,3.9,1.3,0.4,Iris-setosa,0.624231
9,5.1,3.3,1.7,0.5,Iris-setosa,0.655210
11,5.4,3.9,1.7,0.4,Iris-setosa,0.745769
0,5.4,3.4,1.7,0.2,Iris-setosa,0.781548
5,5.0,3.4,1.6,0.4,Iris-setosa,0.879404
8,5.1,3.7,1.5,0.4,Iris-setosa,1.210506
3,5.4,3.7,1.5,0.2,Iris-setosa,1.405898
6,5.3,3.7,1.5,0.2,Iris-setosa,1.692439
4,5.1,3.5,1.4,0.3,Iris-setosa,1.901307
1,5.2,3.4,1.4,0.2,Iris-setosa,1.976392
2,5.2,3.5,1.5,0.2,Iris-setosa,2.306650
7,5.1,3.4,1.5,0.2,Iris-setosa,2.555327

### Insight 2: Which Features Contributed?

In addition to providing attribution to cases, Howso also provides robust feature contributions to explain which features contributed to each prediction.
When inspecting the feature importances for case `13`,  we see that `petal width` and `petal length` provided the majority of the contribution to the 
prediction, whereas for case `20` `petal width` and `petal length` only have slightly higher contributions than the other features.  This could indicate 
that different features are more important for predicting different classes within this dataset and that focusing on those features would be prudent.

Identifying that certain cases that influenced a prediction are anomalous can help to explain low predictive power in certain parts of the data or other
issues that may appear during deployment.

In [11]:
fcs_13 = reaction["details"]["feature_robust_prediction_contributions"][13:14]
fcs_20 = reaction["details"]["feature_robust_prediction_contributions"][20:21]

display(fcs_13)
display(fcs_20)

,sepal width,petal length,petal width,sepal length
13,"[0.05816064779416448, None, 0]","[0.26076170745706645, None, 0]","[0.2562662829293402, None, 0]","[0.10760522764341418, None, 0]"

,sepal width,petal length,petal width,sepal length
20,"[0.07818995302566722, None, 0]","[0.14947482775064044, None, 0]","[0.154607555404876, None, 0]","[0.09660357699218836, None, 0]"

### Insight 3: How Certain is the Prediction?

[Residuals](https://docs.howso.com/en/release-latest/user_guide/basic_capabilities/residuals.html) can characterize the uncertainty of the data around the prediction.  This will tell us which features are hard to predict in the region of the data around each case we're predicting.
If a prediction is less accurate than expected, this can explain which features were noisy and may have contributed to the problem.

In [12]:
reaction["details"]["feature_robust_prediction_contributions"]

,sepal width,petal length,petal width,sepal length
0,"[0.04744523807993254, None, 0]","[0.36332751815832715, None, 0]","[0.308406879622815, None, 0]","[0.08348129938846792, None, 0]"
1,"[0.06275255974952834, None, 0]","[0.26359752158571365, None, 0]","[0.26519316110196456, None, 0]","[0.11548523501521805, None, 0]"
2,"[0.034257676727866906, None, 0]","[0.24206834253222825, None, 0]","[0.27195343826805385, None, 0]","[0.07144491922999466, None, 0]"
3,"[0.04782433935602577, None, 0]","[0.23167689674697253, None, 0]","[0.289198866616426, None, 0]","[0.09723126207108732, None, 0]"
4,"[0.061527163941090535, None, 0]","[0.2621387442496198, None, 0]","[0.24897189419593233, None, 0]","[0.07785363971264941, None, 0]"
5,"[0.04433559029766192, None, 0]","[0.20564947857057528, None, 0]","[0.2097676692970573, None, 0]","[0.0881578802999103, None, 0]"
6,"[0.04331686281921672, None, 0]","[0.2044598843880741, None, 0]","[0.20974745064763306, None, 0]","[0.15692878816835273, None, 0]"
7,"[0.033355585700090604, None, 0]","[0.24766402170234078, None, 0]","[0.26142221039011, None, 0]","[0.09244672319797705, None, 0]"
8,"[0.0612290586989231, None, 0]","[0.2665202766007084, None, 0]","[0.2522747246120352, None, 0]","[0.06639028442840486, None, 0]"
9,"[0.07503800150761766, None, 0]","[0.21861094868110603, None, 0]","[0.19128389939055543, None, 0]","[0.04947648388642659, None, 0]"
10,"[0.048637900714648886, None, 0]","[0.24266476433031622, None, 0]","[0.3479324360336782, None, 0]","[0.14341179037212165, None, 0]"
11,"[0.05216605460797526, None, 0]","[0.22482861938275694, None, 0]","[0.24377084198673282, None, 0]","[0.08473187138023004, None, 0]"
12,"[0.02522217149301318, None, 0]","[0.1949358562912908, None, 0]","[0.19684562085493656, None, 0]","[0.14707755391843363, None, 0]"
13,"[0.05816064779416448, None, 0]","[0.26076170745706645, None, 0]","[0.2562662829293402, None, 0]","[0.10760522764341418, None, 0]"
14,"[0.03148102866263012, None, 0]","[0.2556054819829247, None, 0]","[0.24679465840585904, None, 0]","[0.06668387993711133, None, 0]"
15,"[0.0325469541143496, None, 0]","[0.166436805103306, None, 0]","[0.168842488313722, None, 0]","[0.16460438086331633, None, 0]"
16,"[0.08414917364633517, None, 0]","[0.14659430262392834, None, 0]","[0.14973704103769, None, 0]","[0.0764473856607452, None, 0]"
17,"[0.08177073878369065, None, 0]","[0.20686257315165993, None, 0]","[0.2967231250095275, None, 0]","[0.11923379396452001, None, 0]"
18,"[0.03202516162272624, None, 0]","[0.2463903973559217, None, 0]","[0.2517902145577055, None, 0]","[0.09626829415215651, None, 0]"
19,"[0.08183083988032035, None, 0]","[0.2343430735816355, None, 0]","[0.22306614280578324, None, 0]","[0.0873534725544736, None, 0]"
20,"[0.07818995302566722, None, 0]","[0.14947482775064044, None, 0]","[0.154607555404876, None, 0]","[0.09660357699218836, None, 0]"
21,"[0.04161424658626076, None, 0]","[0.22535026279555764, None, 0]","[0.2276675208827089, None, 0]","[0.049404599377235826, None, 0]"
22,"[0.06468749278633883, None, 0]","[0.2230634169242613, None, 0]","[0.19929102601940454, None, 0]","[0.05781289142345719, None, 0]"
23,"[0.060702852492573345, None, 0]","[0.1553873699744909, None, 0]","[0.15042890709311424, None, 0]","[0.09659081356437049, None, 0]"
24,"[0.018672103861998645, None, 0]","[0.16413929182519754, None, 0]","[0.15692306691540497, None, 0]","[0.1616029541948278, None, 0]"
25,"[0.05783796979483751, None, 0]","[0.27516864056251233, None, 0]","[0.2923813169995046, None, 0]","[0.10380727398062188, None, 0]"
26,"[0.032386832592488084, None, 0]","[0.24783062440552867, None, 0]","[0.2573160084177699, None, 0]","[0.0685019443537767, None, 0]"
27,"[0.04381266873993251, None, 0]","[0.2688758330649234, None, 0]","[0.23332188605395443, None, 0]","[0.07048050659399492, None, 0]"
28,"[0.029630768211490167, None, 0]","[0.2443605315475288, None, 0]","[0.23726769618950588, None, 0]","[0.09522230831493747, None, 0]"
29,"[0.03138498102080015, None, 0]","[0.2527027060754326, None, 0]","[0.23134396153022188, None, 0]","[0.11251909165899956, None, 0]"

We can also use [`residual conviction`](https://docs.howso.com/en/release-latest/user_guide/basic_capabilities/conviction.html#prediction-residual-conviction) to determine which features
are uncertain in a scale-invariant manner, which can be useful if you wish to compare different features of different scales against each other.  Higher residual conviction
indicates something that is less surprising than expected and lower redsidual conviction indicates the opposite.

In [13]:
reaction["details"]["feature_full_residual_convictions_for_case"]

    sepal width  petal length      class  petal width  sepal length
0      0.980469      0.615074   1.110545     2.501187      0.989008
1      0.602311      0.855498   1.739868     1.001842      0.965016
2      2.353527      0.480217   1.568561     1.109753      0.672328
3      0.737917      3.648855  13.162833     4.954465      1.057624
4      2.089854      0.386466   0.598596     0.392744      0.539602
5      0.635704      3.525373   0.003063     1.628277      1.504318
6      0.575459      1.038469   0.003063     1.628381      0.866086
7      0.611200      0.858490   2.095899     3.421518      0.912567
8      0.537637      1.676710   5.886638     0.833328      0.754313
9      0.352500      1.976641   2.142474     0.864314      1.836994
10     1.729622      3.367872  21.809841     1.886218      1.283490
11     1.116101      0.786155  10.881947     0.875795      0.578383
12     2.355827      2.138833   0.003063     1.378296      1.238710
13     2.013417      2.791432   1.173883     0.967543      2.003579
14     3.052337      0.918937   8.485039     0.419243      2.130790
15     2.070711      0.801420   0.003063     1.362745      0.952424
16     0.717412      0.416745   0.003063     1.180766      0.360823
17     2.982827      0.810825   1.133489     4.307960      4.288366
18     0.328128      0.599534   2.162717     0.494624      2.624848
19     0.891413      0.305079   2.265372     0.290509      0.305996
20     0.373769      1.887185   0.003063     0.350617      0.407712
21     0.574939      2.659412   0.003063     1.865829      3.108603
22     0.260184      2.853641   7.125570     0.511191      0.667519
23     1.576730      2.590083   0.003063     1.434645      1.827974
24     4.335647      0.383538   0.003063     1.750402      6.000597
25     2.672714      0.748234   1.253391     2.876057      2.065453
26     0.378333      1.165953   3.280425     0.425654      3.988765
27     7.261544      6.106775   2.699259     0.833694      2.727851
28     0.868521      3.563083   3.376923     0.874410      1.039324
29     1.464023      1.177924   0.938691     1.676403      0.930687

### Insight 4: How Anomalous are the Predicted Cases?

By getting the [`similarity conviction`](https://docs.howso.com/en/release-latest/user_guide/basic_capabilities/conviction.html#similarity-conviction) of the cases that we predict, 
we can determine which of them are anomalous relative to the trained data. This could help to highlight cases that are unusually difficult or easy to predict, such as can be the case
when model drift occurs as a form of model monitoring.

In [14]:
pprint(reaction["details"]["similarity_conviction"], compact=True)

[1.9334749509492835, 0.9815807983469168, 0.8123050203441791, 0.608404174365475,
 0.49693550145999277, 2.7323446862087546, 1.4284994348304267,
 1.3694792491473022, 0.606736674041754, 1.9831913790307372, 1.4055522104749498,
 0.5316661718574703, 2.8324375607566097, 0.7570272236055251, 0.7843785513747417,
 1.2422709977389415, 0.8297204970346232, 2.0773951850874246, 0.6822518783554194,
 0.33607654675749343, 0.7715239481423417, 2.2930594958495094,
 0.5235124077233211, 1.7447096259276387, 1.346796793183613, 2.066741974394008,
 1.6961116296253553, 1.591580758308647, 0.7003359716578845, 0.709801314287934]

In this case, there are no cases with a low similarity_conviction which indicates that there are no cases that we reacted to which are particularly
anomalous.